// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsb4tzkfFdSb10FB8G_IC9fvM2b7DbLfk',
    appId: '1:1070052475297:web:8cedac77893b4a04328be0',
    messagingSenderId: '1070052475297',
    projectId: 'familychat-55095',
    authDomain: 'familychat-55095.firebaseapp.com',
    storageBucket: 'familychat-55095.appspot.com',
    measurementId: 'G-FE4KC40304',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWrBNkEhd1Ig_IEdKlO6JbPDhYyoebqLM',
    appId: '1:1070052475297:android:df5cf9b788f890f0328be0',
    messagingSenderId: '1070052475297',
    projectId: 'familychat-55095',
    storageBucket: 'familychat-55095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DvqzgqVkafMj_n1pJBwplw5km7CYoV8',
    appId: '1:1070052475297:ios:44ce4befe6b06811328be0',
    messagingSenderId: '1070052475297',
    projectId: 'familychat-55095',
    storageBucket: 'familychat-55095.appspot.com',
    androidClientId: '1070052475297-klh025qv0chqh8e90red4ib22otbq20j.apps.googleusercontent.com',
    iosClientId: '1070052475297-fea7jp7bnt2v9d74icq2fn21011ucjnf.apps.googleusercontent.com',
    iosBundleId: 'com.nayeem.familychat',
  );
}
